version: "3.8"
services:
  db:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    volumes:
      - dbdata:/data/db
    expose:
      - 27017

  web:
    build: .
    image: swc_project/dev
    container_name: node_project
    restart: unless-stopped
    env_file: .env
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    #            - redis
    volumes: 
      - .:/user/src/app/backend
    
    environment:
      - MONGO_URI=mongodb://mongo:27017/SAC_DB
      - WAIT_HOSTS=mongo:27017
  #Uncomment this block if your project needs to use redis
  # redis :
  #     restart: unless-stopped
  #     image : redis:alpine
  #     expose :
  #     - 6379

volumes:
  dbdata:

networks:
  default:
    external:
      name: nginx-proxy